# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Integrative Dentistry
email: info@integrativedentistry.com
description: We practice mercury-safe, biological holistic dentistry with a whole-body approach, providing various cosmetic dental treatments for the entire family in Seattle WA and its surrounding areas. Call @ 206367-6453!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mitchmarderdds.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/IDNewLogoFINAL.png
webmaster_verifications:
  google: zAVjXEpG10ULRWmFeJozeoudsl-Rwz2yT46zEr-MWsg
  bing: E95D4B22FE47F7B2AC8806B27278C1DB


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-redirect-from

# Collections
collections:
  doctors:
  hygienists:
  reviews:
  services:
    output: true
    permalink: /services/:name/
    order:
      - teledentistry.md
      - dental-anxiety-clearing.md
      - airway-optimization.md
      - advanced-prf-platelet-rich-fibrin.md
      - childrens-dentistry.md
      - cosmetic-dentistry.md
      - invisalign.md
      - laser-therapy.md
      - mercury-bpa-free-fillings.md
      - metal-free-dental-implants.md
      - myobrace.md
      - natural-dentistry.md
      - orthodontics.md
      - ozone-therapy.md
      - periodontics.md
      - pinhole-surgical-technique.md
      - plaque-microscopy.md
      - safe-mercury-removal.md
      - saliva-testing.md
      - same-day-ceramic-crowns-and-onlays.md
      - sedation-dentistry.md
      - sleep-apnea-treatment.md
      - swiss-surgical-technique.md
      - tmj-treatment.md
      - zirconia-implants.md
  about-us:
    output: true
    permalink: /about-us/:name/
  blog:
    output: true
    permalink: /blog/
  news:
    output: true
    permalink: /news/:name/

autopages:
  enabled: true
  collections:
    enabled: true

pagination:
  enabled: true
  collection: 'blog'
  per_page: 10
  sort_reverse: true
  permalink: 'page/:num/'

pagination:
  enabled: true
  collection: 'news'
  per_page: 10
  sort_reverse: true
  permalink: 'page/:num/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
