version: 0.1

phases:
  install:
    runtime-versions:
      ruby: 2.6
      nodejs: 10
  build:
    commands:
      - bundle exec jekyll build
      - aws s3 sync --delete _site/ s3://www.mitchmarderdds.com
      - aws cloudfront create-invalidation --distribution-id E1EXFO5KCKC80R --paths '/*'